### ISSUE TITLE
Hello, i need to show text only. But this library take too much size for my sketch, do you have tiny version. Help please 

### ISSUE THREAD

**Issue by harymk** [MajicDesigns/MD_Parola#101]

**Comment by alastaira** [comment]
There are plenty of other MAX7219 libraries available: e.g. https://github.com/wayoda/LedControl

**Comment by MajicDesigns** [comment]
You can turn off aminations that you do not plan to use. Change the #defines ENA_* in the Parola.h header file. This is also documented in the library documentation.

Alternatively you can also just j=use MD_MAX72xx and write more code yourself to dosplay. There is probably an example that does this already.

If neither gives you enough extra memory, then you should use another library.
