### ISSUE TITLE
How to never flip a sprite? (eg. to show a music note symbol)

### ISSUE THREAD

**Issue by x2nie** [MajicDesigns/MD_Parola#102]
Hi ! I am creating a [parola sprite editor](https://github.com/x2nie/parola_font_editor) (for vscode). 
it's works fine for me.

![preview](https://raw.githubusercontent.com/x2nie/parola_font_editor/main/documentation/ver-1.png)

**My question** is: how can I use a sprite without mirroring horizontally with parolla?
explanation: Currently I can  play pacman, and this pacman heading to right when it first running, and heading to left in second time.
I want to use an musical symbol that it should be never mirrored (flipped horizontally).

my code:
```cpp
const uint8_t F_NOTE_F = 1;
const uint8_t W_NOTE_F = 8;
const uint8_t PROGMEM note_f[F_NOTE_F * W_NOTE_F] =  // note_f
{
 0x8e, 0x8d, 0x41, 0x61, 0x3f, 0x1e, 0x00, 0x0a,
};
```

![image](https://user-images.githubusercontent.com/1678529/197404672-71b40de0-6796-46f5-8dae-a8e581d2e74f.png)

**Comment by MajicDesigns** [comment]
At the moment there is no way to do this. The sprite will be turned around by the library when the direction changes.

**Comment by x2nie** [comment]
Hi, finally I found a solution without need of additional function (can work with current MD_Parola).
Well, inspired by `Parola_Animation_Catalog.ino` that show 2 different sprites for one animation, I created a flipped sprite to be shown as "not flipped" (because the second sprite will always flipped horizontally by library).

The idea is to provide 2 sprites, with the second one as flipped from first sprites
```cpp
// Sprite Definition
const uint8_t F_ROCKET = 2;
const uint8_t W_ROCKET = 11;
const uint8_t PROGMEM rocket_launch[F_ROCKET * W_ROCKET] =  // rocket
{
  0x18, 0x24, 0x42, 0x81, 0x99, 0x18, 0x99, 0x18, 0xa5, 0x5a, 0x81,
  0x18, 0x24, 0x42, 0x81, 0x18, 0x99, 0x18, 0x99, 0x24, 0x42, 0x99,
};

const uint8_t PROGMEM rocket_depart[F_ROCKET * W_ROCKET] =  // rocket flipped no-flip
{
  0x81, 0x5a, 0xa5, 0x18, 0x99, 0x18, 0x99, 0x81, 0x42, 0x24, 0x18,
  0x99, 0x42, 0x24, 0x99, 0x18, 0x99, 0x18, 0x81, 0x42, 0x24, 0x18,
};
```

The full source-code below can be shown (as live / online simulation) here : https://wokwi.com/projects/346387200800195154
![image](https://user-images.githubusercontent.com/1678529/197481929-4ace42d7-1345-42bc-9c0e-0fd8261f7610.png)


full code:
```cpp
// Program to exercise the MD_Parola library
//
// Demonstrates an un-flpped sprite.
// a demo solution of question : https://github.com/MajicDesigns/MD_Parola/issues/102
//
// MD_MAX72XX library can be found at https://github.com/MajicDesigns/MD_MAX72XX
//

#include <MD_Parola.h>
#include <MD_MAX72xx.h>
#include <SPI.h>

// Define the number of devices we have in the chain and the hardware interface
// NOTE: These pin numbers will probably not work with your hardware and may
// need to be adapted
#define HARDWARE_TYPE MD_MAX72XX::PAROLA_HW
#define MAX_DEVICES 11

#define CLK_PIN   13
#define DATA_PIN  11
#define CS_PIN    10

// HARDWARE SPI
MD_Parola P = MD_Parola(HARDWARE_TYPE, CS_PIN, MAX_DEVICES);
// SOFTWARE SPI
//MD_Parola P = MD_Parola(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);

// Global variables
const char msg[] = "Parola Sprites";

// Sprite Definition
const uint8_t F_ROCKET = 2;
const uint8_t W_ROCKET = 11;
const uint8_t PROGMEM rocket_launch[F_ROCKET * W_ROCKET] =  // rocket
{
  0x18, 0x24, 0x42, 0x81, 0x99, 0x18, 0x99, 0x18, 0xa5, 0x5a, 0x81,
  0x18, 0x24, 0x42, 0x81, 0x18, 0x99, 0x18, 0x99, 0x24, 0x42, 0x99,
};

const uint8_t PROGMEM rocket_depart[F_ROCKET * W_ROCKET] =  // rocket flipped no-flip
{
  0x81, 0x5a, 0xa5, 0x18, 0x99, 0x18, 0x99, 0x81, 0x42, 0x24, 0x18,
  0x99, 0x42, 0x24, 0x99, 0x18, 0x99, 0x18, 0x81, 0x42, 0x24, 0x18,
};

void setup(void)
{
  P.begin();
  P.displayText(msg, PA_CENTER, P.getSpeed(), 1000, PA_SPRITE, PA_SPRITE);
  P.setSpriteData(rocket_launch, W_ROCKET, F_ROCKET, rocket_depart, W_ROCKET, F_ROCKET);
}

void loop(void)
{
  if (P.displayAnimate())
    P.displayReset();
}
```

**Comment by x2nie** [comment]
or in easier to see:
![image](https://user-images.githubusercontent.com/1678529/197483401-c1e85ecb-0222-40c7-8b17-09f577fa5eee.png)

**Comment by x2nie** [comment]
Thanks You !
