### ISSUE TITLE
Multiple Row Displays

### ISSUE THREAD

**Issue by TobiasPSP** [MajicDesigns/MD_Parola#108]
First, this is an awesome work,. Have reviewed multiple libs so far, yet this seems to me like the most professional and well-thought concept.

What I cannot seem to find is a way to use multiple rows, i.e. a 8x64 strip and another 8x64 strip to create one display of 16x64. I did look at zones, and also at addressing different strips separately. Yet what I am trying to do is display one text just in a bigger font. 

Is there a way, and could you point me to the appropriate example? I'd greatly appreciate it.

**Comment by MajicDesigns** [comment]
Version 3.7.1 may fix the unreliability issue you reported.
