### ISSUE TITLE
Interrupt text effect in anytime 

### ISSUE THREAD

**Issue by uronito** [MajicDesigns/MD_Parola#112]
Hi, 

First of all I wanted to thank you for your hard work for this great library.

Would it be possible to stop a vertical text scroll effect at any time?

It would be like interrupting the animation at any time

Sometimes I mount a text effect with another.

**Comment by MajicDesigns** [comment]
If you stop calling .displayAnimate() the display will stop animating and 'freeze in place. If you want to clear the current animation you can clear the display/zone using .displayClear() and reset the animation sequence using .displayReset(). Look at the "Methods for core object control" section of the library help file.

**Comment by uronito** [comment]
don't work, here is my code

``
const char* OTA_hostname    = "Panel-led";
const char* OTA_password    = "";      // Don't forget to set your settings!
#include <ArduinoJson.h>

#include <MD_Parola.h>
#include <Time.h>
#include <MD_MAX72xx.h>            // For LED matrix display
#include <SPI.h>                   // For connecting matrix display
#include <PubSubClient.h>          // For MQTT
#include <ESP8266WiFi.h>           // For WiFi connection with ESP8266
#include <WiFiUdp.h>               // For NTP Signal fetch
#include <EasyNTPClient.h>         // For NTP Signal read https://github.com/aharshac/EasyNTPClient
#include <TimeLib.h>// For converting NTP time https://github.com/PaulStoffregen/Time.git
#include <ArduinoOTA.h>
#include "OTA_update.hpp"
#include "Font_Data.h"
#include "Settings.h"
#define HARDWARE_TYPE MD_MAX72XX::FC16_HW
#define MAX_DEVICES 8
#define MAX_ZONES 3


unsigned long timing;




#define CLK_PIN   14
#define DATA_PIN  13
#define CS_PIN    15
char  szMesg[21] = "";
int pirSensor = 5;                               // Pin, where PIR sensor is connected
bool nuevo_mensaje = false;
#define SPEED_TIME  45
#define PAUSE_TIME  1000
bool encendido;
bool tres_zonas;








WiFiUDP udp;
EasyNTPClient ntpClient(udp, NTP_SERVER, TZ_SEC);

MD_Parola P = MD_Parola(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);


MD_MAX72XX *mx;






void(* resetFunc) (void) = 0;       // declare reset function @ address 0

WiFiClient espClient;               // needed for MQTT
PubSubClient mqtt_client(espClient);     // needed for MQTT


// Global variables
uint8_t  curText;

uint8_t degC[] = { 6, 3, 3, 56, 68, 68, 68 };

String tempvar;

char actualtime[16];
char actualseconds[16];
char actualday[90];
char outdoortemp[2048];
char pooltemp[512];
char indoortemp[512];
char zambrettiswords[512];
char trend[512];
char *mqtterror = "MQTT Error";
char *wifierror = "WiFi Error";
char mensaje_mosquito[2048];
int verde = D6;
int rojo = D4;


const char *msg[] =
{
  "",
  "",
  "",
  "",
  "",
  "",
  ""
};

unsigned long timestamp;
unsigned long timebuffer;
int periodo = 1000;
unsigned long TiempoAhora = 0;

/* displayClear() = alle Zonen löschen
  textEffect_t  effect[] =
  {
  PA_RANDOM,
  PA_PRINT,
  PA_SCAN_HORIZ,
  PA_SCROLL_LEFT,
  PA_WIPE,
  PA_SCAN_VERTX,
  PA_SCROLL_UP_LEFT,
  PA_SCROLL_UP,
  PA_FADE,
  PA_OPENING_CURSOR,
  PA_GROW_UP,
  PA_SCROLL_UP_RIGHT,
  PA_BLINDS,
  PA_SPRITE,
  PA_CLOSING,
  PA_GROW_DOWN,
  PA_SCAN_VERT,
  PA_SCROLL_DOWN_LEFT,
  PA_WIPE_CURSOR,
  PA_SCAN_HORIZX,
  PA_DISSOLVE,
  PA_MESH,
  PA_OPENING,
  PA_CLOSING_CURSOR,
  PA_SCROLL_DOWN_RIGHT,
  PA_SCROLL_RIGHT,
  PA_SLICE,
  PA_SCROLL_DOWN,
  };*/

// Sprite Definitions
const uint8_t F_PMAN1 = 6;
const uint8_t W_PMAN1 = 8;
static const uint8_t PROGMEM pacman1[F_PMAN1 * W_PMAN1] =  // gobbling pacman animation
{
  0x00, 0x81, 0xc3, 0xe7, 0xff, 0x7e, 0x7e, 0x3c,
  0x00, 0x42, 0xe7, 0xe7, 0xff, 0xff, 0x7e, 0x3c,
  0x24, 0x66, 0xe7, 0xff, 0xff, 0xff, 0x7e, 0x3c,
  0x3c, 0x7e, 0xff, 0xff, 0xff, 0xff, 0x7e, 0x3c,
  0x24, 0x66, 0xe7, 0xff, 0xff, 0xff, 0x7e, 0x3c,
  0x00, 0x42, 0xe7, 0xe7, 0xff, 0xff, 0x7e, 0x3c,
};

const uint8_t F_PMAN2 = 6;
const uint8_t W_PMAN2 = 18;
static const uint8_t PROGMEM pacman2[F_PMAN2 * W_PMAN2] =  // ghost pursued by a pacman
{
  0x00, 0x81, 0xc3, 0xe7, 0xff, 0x7e, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x7b, 0xf3, 0x7f, 0xfb, 0x73, 0xfe,
  0x00, 0x42, 0xe7, 0xe7, 0xff, 0xff, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x7b, 0xf3, 0x7f, 0xfb, 0x73, 0xfe,
  0x24, 0x66, 0xe7, 0xff, 0xff, 0xff, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x7b, 0xf3, 0x7f, 0xfb, 0x73, 0xfe,
  0x3c, 0x7e, 0xff, 0xff, 0xff, 0xff, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x73, 0xfb, 0x7f, 0xf3, 0x7b, 0xfe,
  0x24, 0x66, 0xe7, 0xff, 0xff, 0xff, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x73, 0xfb, 0x7f, 0xf3, 0x7b, 0xfe,
  0x00, 0x42, 0xe7, 0xe7, 0xff, 0xff, 0x7e, 0x3c, 0x00, 0x00, 0x00, 0xfe, 0x73, 0xfb, 0x7f, 0xf3, 0x7b, 0xfe,
};


const uint8_t F_HEART = 5;
const uint8_t W_HEART = 9;
const uint8_t PROGMEM heart[F_HEART * W_HEART] =  // beating heart
{
  0x0e, 0x11, 0x21, 0x42, 0x84, 0x42, 0x21, 0x11, 0x0e,
  0x0e, 0x1f, 0x33, 0x66, 0xcc, 0x66, 0x33, 0x1f, 0x0e,
  0x0e, 0x1f, 0x3f, 0x7e, 0xfc, 0x7e, 0x3f, 0x1f, 0x0e,
  0x0e, 0x1f, 0x33, 0x66, 0xcc, 0x66, 0x33, 0x1f, 0x0e,
  0x0e, 0x11, 0x21, 0x42, 0x84, 0x42, 0x21, 0x11, 0x0e,
};

const uint8_t F_INVADER = 2;
const uint8_t W_INVADER = 10;
const uint8_t PROGMEM invader[F_INVADER * W_INVADER] =  // space invader
{
  0x0e, 0x98, 0x7d, 0x36, 0x3c, 0x3c, 0x36, 0x7d, 0x98, 0x0e,
  0x70, 0x18, 0x7d, 0xb6, 0x3c, 0x3c, 0xb6, 0x7d, 0x18, 0x70,
};

const uint8_t F_WAVE = 14;
const uint8_t W_WAVE = 14;
const uint8_t PROGMEM wave[F_WAVE * W_WAVE] =  // triangular wave / worm
{
  0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10,
  0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20,
  0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40,
  0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,
  0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40,
  0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20,
  0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10,
  0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08,
  0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02, 0x04,
  0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x02,
  0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01,
  0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02,
  0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04,
  0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x40, 0x20, 0x10, 0x08,
};
const uint8_t F_FBALL = 2;
const uint8_t W_FBALL = 11;
const uint8_t PROGMEM fireball[F_FBALL * W_FBALL] =  // fireball
{
  0x7e, 0xab, 0x54, 0x28, 0x52, 0x24, 0x40, 0x18, 0x04, 0x10, 0x08,
  0x7e, 0xd5, 0x2a, 0x14, 0x24, 0x0a, 0x30, 0x04, 0x28, 0x08, 0x10,
};

const uint8_t F_ROLL1 = 4;
const uint8_t W_ROLL1 = 8;
const uint8_t PROGMEM roll1[F_ROLL1 * W_ROLL1] =  // rolling square
{
  0xff, 0x8f, 0x8f, 0x8f, 0x81, 0x81, 0x81, 0xff,
  0xff, 0xf1, 0xf1, 0xf1, 0x81, 0x81, 0x81, 0xff,
  0xff, 0x81, 0x81, 0x81, 0xf1, 0xf1, 0xf1, 0xff,
  0xff, 0x81, 0x81, 0x81, 0x8f, 0x8f, 0x8f, 0xff,
};

const uint8_t F_ROLL2 = 4;
const uint8_t W_ROLL2 = 8;
const uint8_t PROGMEM roll2[F_ROLL2 * W_ROLL2] =  // rolling octagon
{
  0x3c, 0x4e, 0x8f, 0x8f, 0x81, 0x81, 0x42, 0x3c,
  0x3c, 0x72, 0xf1, 0xf1, 0x81, 0x81, 0x42, 0x3c,
  0x3c, 0x42, 0x81, 0x81, 0xf1, 0xf1, 0x72, 0x3c,
  0x3c, 0x42, 0x81, 0x81, 0x8f, 0x8f, 0x4e, 0x3c,
};


struct
{
  const uint8_t *data;
  uint8_t width;
  uint8_t frames;
}
sprite[] =
{

  //{ walker, W_WALKER, F_WALKER },
  { invader, W_INVADER, F_INVADER },
  //{ chevron, W_CHEVRON, F_CHEVRON },
  { heart, W_HEART, F_HEART },
  //{ arrow1, W_ARROW1, F_ARROW1 },
  //{ steamboat, W_STEAMBOAT, F_STEAMBOAT },
  { fireball, W_FBALL, F_FBALL },
  //{ rocket, W_ROCKET, F_ROCKET },
  { roll2, W_ROLL2, F_ROLL2 },
  { pacman2, W_PMAN2, F_PMAN2 },
  //{ lines, W_LINES, F_LINES },
  { roll1, W_ROLL1, F_ROLL1 },
  //{ sailboat, W_SAILBOAT, F_SAILBOAT },
  //{ arrow2, W_ARROW2, F_ARROW2 },
  { wave, W_WAVE, F_WAVE },
  //{ pacman1, W_PMAN1, F_PMAN1 }
};


static uint8_t display = 0;  // current display mode


void setup(void)
{


  Serial.begin(115200);
  Serial.println();
  Serial.println("Starting MQTT LED Monitor");

  go_online();                    // open WiFi and go online
  // connect to MQTT mosquitto server on orange pi
  get_NTP_time();


  mqtt_client.setServer(mqtt_server, mqtt_port);
  mqtt_client.setCallback(mqttCallback);
  mqttConnect();

  P.begin(MAX_ZONES);
  mx = P.getGraphicObject(); 
  P.setZone(0, 0, 0);
  P.setZone(1, 1, 3);
  P.setZone(2, 4, 7);
  P.setIntensity(0, 0);
  P.setIntensity(1, 0);
  P.setIntensity(2, 0);

  encendido = false;
  P.setSpriteData(pacman1, W_PMAN1, F_PMAN1, pacman2, W_PMAN2, F_PMAN2);
  P.setCharSpacing(1);
  tres_zonas = false;
  

  setup_ota();// inicializamos ota


}

void loop() {



  if (!mqtt_client.connected())
  {
    mqttConnect();
  }

  mqtt_client.loop();             // MQTT
  ArduinoOTA.handle();
  if (hour(now()) >= 8)
  {
    if (encendido == false)
    {
      
      P.displayShutdown(false);
      encendido = true;
      if (hour(now()) == 8)
      {

      if (P.getZoneStatus(1) && tres_zonas == false )
      {

          
          P.setZone(1, 0, 3);
          P.setZone(2, 4, 7);
         
          
          tres_zonas = false;
      }
        P.setFont(1, BigFontLower);
        P.setFont(2, BigFontUpper);
       P.setCharSpacing(1);
        P.setIntensity(1, 10);
        P.setIntensity(2, 10);
        P.synchZoneStart();

        
        P.displayZoneText(2, "Buenos dias!!!" , PA_RIGHT, SPEED_TIME, 310, PA_SCROLL_LEFT,  PA_MESH    );
        
        P.displayZoneText(1, "Buenos dias!!!" , PA_RIGHT, SPEED_TIME, 310, PA_SCROLL_LEFT,  PA_MESH     );
        

      }

    }
  
    
          
         
        
    if (P.displayAnimate())
    {
       
      
      
        
      
      
      static uint8_t  curFX = 1;
      TiempoAhora = millis();

      timebuffer = 120000;
      static bool  flasher = false;
      static uint32_t  lastTime = 0;
      static uint32_t  lastTime2 = 0;


      //if (millis() - lastTime >= 1000)
      //{
      //  lastTime = millis();
      //  flasher = !flasher;
      //}

      
      sprintf(actualtime, "%02d%c%02d%c", hour(now()), (second(now())%2==0 ? ':' : ' '), minute(now()),(second(now())%2==0 ? ':' : ' '));
      sprintf(actualseconds, "%02d", second(now()));
      
     

     if (P.getZoneStatus(1) && tres_zonas == false )
      {

          P.setZone(0, 0, 0);
          P.setZone(1, 1, 3);
          P.setZone(2, 4, 7);
          P.setIntensity(0, 0);
          P.setIntensity(1, 0);
          P.setIntensity(2, 0);
          tres_zonas = true;
      }
      
      
      if (P.getZoneStatus(1))
                
      {
        
              P.setFont(0, numeric7Seg);
              if (P.getZoneStatus(0) && P.displayAnimate())
              {
                 P.displayZoneText(0, actualseconds , PA_LEFT, SPEED_TIME, 305, PA_SCROLL_DOWN   , PA_SCROLL_DOWN );
                  //P.displayZoneText(0, actualseconds , PA_LEFT, SPEED_TIME, 0, PA_NO_EFFECT   , PA_NO_EFFECT );
                  P.displayAnimate();
              }
              
             
              P.setFont(1, numeric7Se);
              P.displayZoneText(1, actualtime , PA_LEFT, SPEED_TIME, 0, PA_NO_EFFECT , PA_NO_EFFECT );
              P.displayAnimate();
        
          
        
      }

      
      
      if (P.getZoneStatus(2))
      {

        if (millis() - lastTime2 >= 60000)
        {
          P.setIntensity(2, 0);
          P.setIntensity(1, 0);
          P.setFont(2, jF_Custom);
          lastTime2 = millis();


          String dia = dayStr(weekday());
          String mes = monthStr(month());
          //sprintf(actualday, "%02s%c%02d%s%02s%s%02d",dayStr(weekday()),',', day()," de ",monthStr(month()), " de ", year());
          sprintf(actualday, "%1s, %02d de %2s de %02d", dia , day(), mes , year());
          P.displayZoneText(2, actualday, PA_LEFT, 50, 300, PA_SCROLL_LEFT , PA_MESH  );
          P.displayAnimate();
















        }
        else
        {
         
         
              if (P.displayAnimate())
              {
                        P.setFont(2, nullptr);
                        P.setIntensity(0, 0);
                        P.setIntensity(2, 0);
                        P.setIntensity(1, 0);
                        if (curFX == 1)
                        {
                          P.setSpriteData(2, pacman1, W_PMAN1, F_PMAN1, pacman2, W_PMAN2, F_PMAN2);
                        }
                        else
                        {
                          P.setSpriteData(2, sprite[curFX].data, sprite[curFX].width, sprite[curFX].frames, // entry sprite
                                          sprite[curFX].data, sprite[curFX].width, sprite[curFX].frames); // exit sprite
                        }
              
                        P.displayZoneText(2, msg[curFX], PA_CENTER, SPEED_TIME, PAUSE_TIME, PA_SPRITE, PA_SPRITE);
                        curFX = (curFX + 1) % ARRAY_SIZE(sprite);
                        P.displayAnimate();
              }
        encendido = true;
        }
      }
      
      
    }
  }
  else
  {
     if (P.displayAnimate() && hour(now()) == 0 )
    {
       if (encendido == true)
       {
            P.displayClear();
            P.displayShutdown(false);
            P.setZone(1, 0, 3);
            P.setZone(2, 4, 7);
            
            P.setFont(1, BigFontLower);
            P.setFont(2, BigFontUpper);
            P.setCharSpacing(1);
            P.setIntensity(1, 10);
            P.setIntensity(2, 10);
            
            P.synchZoneStart();
            

          
         
         
         
          tres_zonas = false;
      
            P.displayZoneText(2, "Buenas noches!!!" , PA_RIGHT, SPEED_TIME, 200, PA_SCROLL_LEFT,  PA_MESH    );
            P.displayZoneText(1, "Buenas noches!!!" , PA_RIGHT, SPEED_TIME, 200, PA_SCROLL_LEFT,  PA_MESH     );
            P.displayAnimate();
            
              encendido = false;  
            
       }
       else
       {
        if (P.displayAnimate())
        {
          if (P.getZoneStatus(1))
            {
                
                   P.displayShutdown(true);
                
            }
        }
       }
            
           
     
       
    }
    
  }


  if ((now() - timestamp) > 86400)
  { // 86400 seconds = 24 hours
    get_NTP_time();                        // get all 24 hours a time update from NTP Server --> avoiding a constant read from time server
  }

}


void go_online() {
  WiFi.mode(WIFI_STA);
  WiFi.hostname("MQTTLEDDISPLAY");     //This changes the hostname of the ESP8266 to display neatly on the network esp on router.
  WiFi.begin(ssid, pass);
  Serial.print("---> Connecting to WiFi ");
  int i = 0;
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    i++;
    if (i > 20) {
      Serial.println("Could not connect to WiFi!");
      Serial.println("Doing a reset now and retry a connection from scratch.");

      P.displayZoneText(0, wifierror, PA_CENTER, SPEED_TIME, PAUSE_TIME, PA_PRINT, PA_NO_EFFECT); // send error message to display
      P.displayAnimate();
      P.displayReset(0);
      delay(60000);        // wait one minute, then do a reset and try again
      resetFunc();
    }
    Serial.print(".");
  }
  Serial.println("Wifi connected ok.");

  digitalWrite(rojo, HIGH);
} //end go_online

void get_NTP_time() {

  Serial.println("---> Now reading time from NTP Server");

  while (!ntpClient.getUnixTime()) {
    delay(100);
    Serial.print(".");
  }
  setTime(ntpClient.getUnixTime());           // get UNIX timestamp (seconds from 1.1.1970 on)

  if (summertime_EU(year(now()), month(now()), day(now()), hour(now()), 1)) {
    adjustTime(3600);                         // adding one hour
  }

  timestamp = now();




  delay(50);

} // end get_NTP_time()

void mqttConnect() {
  // Loop until we're reconnected
  while (!mqtt_client.connected()) {
    // Attempt to connect
    if (mqtt_client.connect("ESP-PANELLED", mqtt_username, mqtt_password)) {
      mqtt_client.subscribe("domoticz/out");
      digitalWrite(12, HIGH);
      Serial.print("Estoy conectado a mqtt");

    } else {
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}




void mqttCallback(char* topic, byte* message, unsigned int length) {






 
  Serial.print("Message arrived on topic: ");
  Serial.print(topic);
  Serial.print(". Message: ");
  String messageTemp;
  for (int i = 0; i < length; i++) {
    //Serial.print((char)message[i]);
    messageTemp += (char)message[i];
  }
  Serial.print(messageTemp);


  if (String(topic) == "domoticz/out") {
    tempvar = messageTemp;
    char mensaje_acumulador[2048];
    tempvar.toCharArray(mensaje_acumulador, 2048);
    DynamicJsonDocument doc(2048);
    deserializeJson(doc, mensaje_acumulador);

    bool prueba = doc.containsKey("name");
    if (prueba)
    {
      String comprobador_name = doc["name"];
      if (comprobador_name.indexOf("Enchufe") > -1 || comprobador_name.indexOf("Recreativa") > -1 || comprobador_name.indexOf("Persiana") > -1 || comprobador_name.indexOf("Puerta") > -1     || comprobador_name.indexOf("movimiento") > -1 || comprobador_name.indexOf("Altavoz") > -1  )
      {
        
        if (comprobador_name == "Sensor Puerta")
        {
          comprobador_name = "Puerta";
        }
        if (comprobador_name.indexOf("Recreativa") > -1)
        {
          if (comprobador_name.indexOf("Interruptor") > -1)
          {
            comprobador_name = "Recreativa";
          }
        }
        String comprobador_dtype = doc["dtype"];
        if (comprobador_dtype.indexOf("Light") > -1 || comprobador_dtype.indexOf("Switch") > -1 )
        {
          String comprobador_nvalue = doc["nvalue"];
          String cadena_comprobador;

          if (comprobador_nvalue == "0")
          {
            if (comprobador_name.indexOf("Puerta") > -1  || comprobador_name.indexOf("Persiana") > -1 )
            {
              cadena_comprobador = "cerrada";
            }
            else
            {
              cadena_comprobador = "apagado";
            }
          }
          if (comprobador_nvalue == "1")
          {
            if (comprobador_name.indexOf("Puerta") > -1  || comprobador_name.indexOf("Persiana") > -1 )
            {
              cadena_comprobador = "abierta";
            }
            else
            {
              cadena_comprobador = "encendido";
            }
          }
          if (comprobador_nvalue != "1" && comprobador_nvalue != "0")
          {
            cadena_comprobador = "ajustado a ";
            String n_value = doc["nvalue"];
            cadena_comprobador.concat(n_value);
          }
          String sensor;
          sensor.concat(comprobador_name);
          sensor.concat(" ");
          sensor.concat(cadena_comprobador);
          sensor.toCharArray(mensaje_mosquito, 2048);
          nuevo_mensaje = true;

          //memcpy(mensaje_mosquito,sensor,sizeof(sensor));
          //Serial.print(mensaje_mosquito);
           P.displayShutdown(false);
           
          
          //P.setZoneEffect(0,false,PA_NO_EFFECT)

         // P.setZone(0,NULL,NULL);
              P.setZone(0,0,0);
              P.setZone(1, 0, 3);
              P.setZone(2, 4, 7);
              P.displayClear(0);
              P.displayClear(1);
              P.displayClear(2);
              mx->clear(0); 
              mx->clear(0); 
              mx->clear(0); 
              mx->clear(0); 
              mx->clear(0); 
             
          
         
           
         
        
        
         
          
          
                P.setFont(1, BigFontLower);
                P.setFont(2, BigFontUpper);
                P.setCharSpacing(P.getCharSpacing() * 1);
      
                P.setIntensity(1, 10);
                P.setIntensity(2, 10);
                P.displayZoneText(1, mensaje_mosquito , PA_RIGHT, SPEED_TIME, SPEED_TIME, PA_SCROLL_LEFT,  PA_MESH    );
                P.displayZoneText(2, mensaje_mosquito , PA_RIGHT, SPEED_TIME, SPEED_TIME, PA_SCROLL_LEFT, PA_MESH     );
                P.synchZoneStart();
                P.displayAnimate();
                tres_zonas = false;
               
          
          
          
          
          
         
        
          
          
           
         



        }
      }
    }

  }
         
}

boolean summertime_EU(int year, byte month, byte day, byte hour, byte tzHours)
// European Daylight Savings Time calculation by "jurs" for German Arduino Forum
// input parameters: "normal time" for year, month, day, hour and tzHours (0=UTC, 1=MEZ)
// return value: returns true during Daylight Saving Time, false otherwise
{
  if (month < 3 || month > 10) return false; // keine Sommerzeit in Jan, Feb, Nov, Dez
  if (month > 3 && month < 10) return true;  // Sommerzeit in Apr, Mai, Jun, Jul, Aug, Sep
  if (month == 3 && (hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7)) || month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7)))
    return true;
  else
    return false;
}

``

**Comment by MajicDesigns** [comment]
Sorry, but I really don't have time to analyse your code. If you can reduce it to a MINIMAL code set that just uses the Parola library and still does not work then I can replicate this and check what is happening.
