### ISSUE TITLE
Is there a way to access the framebuffer directly?

### ISSUE THREAD

**Issue by adipascu** [MajicDesigns/MD_Parola#126]
Is there a way to access the framebuffer directly?
I am interested in using a different chip than `max72xx` and wish to use MD_Parola for rendering.

This is more of a feature request, [it seems like currently the max72xx is mandatory](https://github.com/MajicDesigns/MD_Parola/blob/72021746b75b71a0f2e99614c61bcec228cd03da/src/MD_Parola.h#L2168) to use `MD_Parola`.

**Comment by MajicDesigns** [comment]
No, the two are paired up as this is such a specialist application. You can create a replacement for the MD_MAX72xx library with the same interface and it would work.
