### ISSUE TITLE
" 'MD_Parola.h' not found"

### ISSUE THREAD

**Issue by tuck9117** [MajicDesigns/MD_Parola#130]
## IMPORTANT
Before submitting this issue
[ ] Have you tried using the latest version of the library?
[ ] Have you checked this has not already been submitted and/or resolved?
[ ] If you are requesting help a better choice may be the [Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
Describe your issue here.
When compiling I receive an error for that " 'MD_Parola.h' not found" after it is already included at the top of the program

## Your Environment
**Library Version:** 
**Arduino IDE version:** 
**Host OS and Version:** 
**CPU Hardware model/type:** 

## Steps to Reproduce
Explain how to reproduce this issue. Please provide working code below to demonstrate the issue.

## Expected Behaviour
Explain what should happen.

## Actual Behaviour
Explain what happens instead. Provide log messages if relevant.

## Code Demonstrating the Issue
````
Insert your compilable code code here (no code snippets).
````

**Comment by MajicDesigns** [comment]
Did you install the library? You can use the IDE library manager.

**Comment by tuck9117** [comment]
Yes I installed the library through the ide, so far I've ran into this
issue with this library as well as the Adafruit_GFX.h library as well but
when I check the files the .h for both are right there.

**Comment by MajicDesigns** [comment]
I have seen this type of error when the ibrary has been installed in more than one place. Is this a possible problem? Use the Windows Search to see if the file is reported more than once.

Alternatively you can also try reinstalling the IDE.

**Comment by tuck9117** [comment]
Unfortunately I've already tried reinstalling. But I will do a search to
see if it appears in multiple places
