### ISSUE TITLE
Half animation for static informationen

### ISSUE THREAD

**Issue by Fiiti** [MajicDesigns/MD_Parola#18]
Nice, really nice project!
I wonder, how i can use a start animation (e.g. slide to left) but then should the text should stop.

I would like to have an incoming text with a nice animation. But afterwards the Text should be stay focused. And this text did have also updates.
Any chance?

Regards,
Fi

**Comment by MajicDesigns** [comment]
Animate with no exit animation, then just use the print animation to update the text when needed.
