### ISSUE TITLE
error message upgrading to version=2.7.0

### ISSUE THREAD

**Issue by pacav69** [MajicDesigns/MD_Parola#19]
i got this error message whilst upgrading the library filename has a + in it 'Parola_Test_T+G'

Enclosed screenshot of error
![image](https://user-images.githubusercontent.com/2259579/37907248-43c14608-3150-11e8-91b7-8097f4bf0df6.png)

**Comment by MajicDesigns** [comment]
Hmm, what an unnecessary restriction in the IDE. Changed file name to TG and released as V2.7.1

**Comment by pacav69** [comment]
great you can lose this issue
