### ISSUE TITLE
dependancy on MD_UISwitch

### ISSUE THREAD

**Issue by pacav69** [MajicDesigns/MD_Parola#20]
While compiling Parola_Test_TG.ino this error occured
/Documents/Arduino/libraries/MD_Parola/examples/Parola_Test_TG/Parola_Test_TG.ino:21:25: fatal error: MD_UISwitch.h: No such file or directory
compilation terminated.

It appears that this library is dependant on 'MD_UISwitch'
It can be fixed by installing MD_UISwitch using the library manager.

**Comment by MajicDesigns** [comment]
Not sure how this is an issue. It clearly states at the top of the .ino file that 
"// UISwitch library can be found at https://github.com/MajicDesigns/MD_UISwitch"

**Comment by pacav69** [comment]
i thought you could place the reminder/warning in the readme file

**Comment by MajicDesigns** [comment]
Every example uses one or more libraries and these are highlighted in the examples. The readme file is not read by most people using the library.
