### ISSUE TITLE
Parola UTF8 disappear

### ISSUE THREAD

**Issue by intel2004** [MajicDesigns/MD_Parola#21]
after trying also this library to understand usage i try first with demo codes:
the example Parola_UTF-8_Display is working if i compile "AS IS"
BUT if i set DEBUG on line 33 to 1 to see in serial whats happening
the display see only Ascii standard in the first part of the code:
"abcABC"
"      "
"50€/kg"
"Espaol"
"30m/s"
"Franais"
"20s/C"
after that 
"128 €"
"129  "
"130 ,"
and so on...
if i reput DEBUG back to 0 the code did not work either! the only way to test the demo is to compile the code without touching it. t is possible?

**Comment by MajicDesigns** [comment]
Not sure what is going on. Using the IDE, as soon as the file is edited the double byte strings seem to be corrupted. Using Visual C with vMicro extension, the program works ok every time, even when edited.

This seems to be a problem with the way the IDE treats the file.
