### ISSUE TITLE
Built error on ESP8266

### ISSUE THREAD

**Issue by AntonWert** [MajicDesigns/MD_Parola#23]
Version 2.7.3 does not built, see below, Version 2.6.6 did without any problem

K:\Arduino\libraries\MD_Parola\src\MD_PZone.cpp: In member function 'void MD_PZone::setSpriteData(uint8_t*, uint8_t, uint8_t, uint8_t*, uint8_t, uint8_t)':

K:\Arduino\libraries\MD_Parola\src\MD_PZone.cpp:98:17: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]

   _spriteInData = inData;

K:\Arduino\libraries\MD_Parola\src\MD_PZone.cpp:101:18: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]

   _spriteOutData = outData;

**Comment by MajicDesigns** [comment]
Ok, Should be fixed now as v2.7.4
