### ISSUE TITLE
line missing in Parola_Print_Test in Arduino IDE

### ISSUE THREAD

**Issue by acestu** [MajicDesigns/MD_Parola#26]
Hi,

If you load the Parola_Print_Test example from the Arduino IDE the following line seems to be missing:

const uint16_t WAIT_TIME = 1000;

If you paste it in under the defines it then compiles without errors

Thanks
Stuart

**Comment by MajicDesigns** [comment]
The example in the repository at [](https://github.com/MajicDesigns/MD_Parola/blob/master/examples/Parola_Print_Test/Parola_Print_Test.ino) seems to have it defined straight after the #includes.

**Comment by acestu** [comment]
Hi, Yes That is where I got it from, I was just letting you know that it is not there if you load the example from Arduino IDE.

thanks
Stuart
