### ISSUE TITLE
led matrix buzzy noise

### ISSUE THREAD

**Issue by arborin** [MajicDesigns/MD_Parola#29]
Hello, 
I am using MAX7219 dot led matrix panel (16x64 combination).

everything working fine, but it has some buzzing noise. 
is there any solution?

**Comment by MajicDesigns** [comment]
None of mine buzz, so I suggest discussing with the hardware supplier.

Or you can wear ear plugs.

**Comment by arborin** [comment]
Take your ironic answer in your asshole. 

I will send ear plugs for your mother! do you want?

Next time be careful for your words.
