### ISSUE TITLE
Parola_Zone_TimeMsg.ino with esp8266

### ISSUE THREAD

**Issue by Dancopy** [MajicDesigns/MD_Parola#44]
What should be changed or added in the "Parola_Zone_TimeMsg.ino" sketch to use with esp8266 (only as a board - not WiFi)? Thank you

**Comment by Dancopy** [comment]
What should be changed or added in the "Parola_Zone_TimeMsg.ino" sketch to use with esp8266 (only as a board - not WiFi)? Thank you

**Comment by MajicDesigns** [comment]
I don't believe that much should be changed from the standard way that the other Arduino boards work. You should probably look at the SPI pin numbers and will need to be careful of the Watchdog timer that will expire if you don't 'feed' it while in loop().

You will need to be more specific if you are having problems, and I would suggest that you ask technical questions on the Arduino forum as there are many other with experience using these libraries on the ESP8266.
