### ISSUE TITLE
reverse characters

### ISSUE THREAD

**Issue by sandwitche** [MajicDesigns/MD_Parola#45]
Hi, I tried this library, the characters show fine, but they are inverted, that means the character starts at the first display on the right side an then the character ends in the second display on the right side. (the first display being the left one.)

this is a picture: http://tinypic.com/view.php?pic=vinn88&s=9 or http://i68.tinypic.com/vinn88.jpg 

I just used the hello world example, and changed the text to "AB".
thanks

**Comment by MajicDesigns** [comment]
Please make sure that you are selecting the right hardware type for your display. There is a lot written in the documentation about this and/or you may want to read this blog post [https://arduinoplusplus.wordpress.com/2017/04/14/parola-a-to-z-adapting-for-different-hardware/](url)
