### ISSUE TITLE
Slot in alternative to MD_MAX72XX?

### ISSUE THREAD

**Issue by matburnham** [MajicDesigns/MD_Parola#60]
Is it possible/easy to use an alternative board to the MAX72xx or is it too tied-in? I'd like to link this library up to my [OctoWS2811 based](https://www.pjrc.com/teensy/td_libs_OctoWS2811.html) system.

**Comment by MajicDesigns** [comment]
In theory this is possible, although I have not tried or heard of it happening elsewhere.

The MD_MAD72xx library provides all the functionality for the hardware management (ie, there is no hardware dependent code in the MD_Parola library). A replacement for MD_MAX72xx that provides the same interfaces/methods used by MD_Parola would need to be written for the new hardware. This is technically 'easy' but there may be other things that come up that are not straightforward (eg, how to handle color).
