### ISSUE TITLE
Opening and Closing animation behaves identical 

### ISSUE THREAD

**Issue by woeperbe** [MajicDesigns/MD_Parola#68]
## Subject of the issue
Opening and Closing animation behaves identical 

## Your Environment
**Library Version: 3.2
**Hardware model/type: NodeMcu FC16
**OS and Version:* Win 10 and Microsoft Visual Studio

## Expected Behaviour
Close should scroll the other way 

## Actual Behaviour
Close animates identical to Open

**Comment by MajicDesigns** [comment]
Please provide the code that shows this problems.

Also make sure you read issue #56.

**Comment by woeperbe** [comment]
Yes I did read that issue #56 

Here is the code :
/******************************************************
******* DISPLAY ANIMATED SHORT STRING *****************
*******************************************************
*/
void DisplayString(char * strng) {

	Matrix.displayText(strng,PA_CENTER, scroll[EEP.scrollmodein].speed * EEP.runspeed,0,scroll[EEP.scrollmodein].effect,PA_NO_EFFECT);
	AnimateMatrix();
	LookDelay(EEP.lookdelay);
	Matrix.displayText(strng,PA_CENTER,scroll[EEP.scrollmodeout].speed * EEP.runspeed,0,PA_PRINT,scroll[EEP.scrollmodeout].effect);
	AnimateMatrix();
}

/******************************************************
******* WAIT TO COMPLETE DISPLAY ANIMATION ************
*******************************************************
*/
void AnimateMatrix(void) {
	bool ret;
	do {
		ret = Matrix.displayAnimate();
		ArduinoOTA.handle();
		server.handleClient();
	} while (!ret);
}

**Comment by MajicDesigns** [comment]
ok. What are the ACTUAL scroll effects you are tyrying to use? What is the value of EEP.scrollmodeout ans EEP.scrollmodein?

**Comment by woeperbe** [comment]
scrollmodein is -->{PA_OPENING,8, "Opening"}
scrollmodeouit --> {PA_CLOSING,8, "Closing"}

it would be nicer if the closing did it from border to middle of display instead of now going like opening from middle to border of the display.

I made a video of this animation mode in and out with PA_OPENING and PA_CLOSING 

https://share.icloud.com/photos/0y4ViqVR9jV2gwpa6x_L2u_ng


![image](https://user-images.githubusercontent.com/45015193/84123933-ccdbbf80-aa3a-11ea-8f96-663e86018229.png)

**Comment by woeperbe** [comment]
i found out that i didn’t understand how the animation for in and out works.
my apologies for the trouble
if i use opening for in and out it works like i would it ....

**Comment by MajicDesigns** [comment]
You discovered what I was going to write.

**Comment by woeperbe** [comment]
thanks for your perfect support .

Greetings,
Marc Buffet


On 9 Jun 2020, at 21:53, Marco Colli <notifications@github.com> wrote:

﻿

You discovered what I was going to write.
