### ISSUE TITLE
Is it possible to print some text aligned left and other text aligned right on the same screen ?

### ISSUE THREAD

**Issue by tavdog** [MajicDesigns/MD_Parola#69]
I have tried issuing multiple P.print/P.write command but the last command always overwrites the first.  I tried messing with the P.getGraphicObject()->control(MD_MAX72XX::UPDATE, MD_MAX72XX::OFF); too but that didn't work.

Any hints ? 
Thanks.

**Comment by MajicDesigns** [comment]
You need to use 2 separate zone, but his also means that you can no longer just use .print but need to use the animation loop technique (even for a PA_PRINT). There are a few multi-zone examples to follow.

**Comment by tavdog** [comment]
When using zones how does that effect drawing pixels directly to the MD_MAX graphics object as in the following
P.getGraphicObject()->setPoint(i, 0, true);   
This type of operation seems to fail when using zones.

**Comment by MajicDesigns** [comment]
It shouldn't fail as the MD_MAX72xx library will just set the pixel. What will happen is that the animation will overwrite the entire zone and whatever you have written to it will need to be redrawn. This is explained in the blog article at https://arduinoplusplus.wordpress.com/2018/03/29/parola-a-to-z-mixing-text-and-graphics/
