### ISSUE TITLE
When inverted, the animation scrolls into unlit matrix, rather than lit matrix.

### ISSUE THREAD

**Issue by subokita** [MajicDesigns/MD_Parola#76]
## IMPORTANT
Before submitting this issue
[X] Have you tried using the latest version of the library?
[X] Have you checked this has not already been submitted and/or resolved?
[X] If you are requesting help a better choice may be the [Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
When inverted, the animation scrolls into unlit matrix, rather than lit matrix.

## Your Environment
**Library Version:** 3.5.2
**Arduino IDE version:** 1.8.13
**Host OS and Version:** OS X Catalina
**CPU Hardware model/type:** Mac Mini 2019
**Matrix hardware model/type:** [ ] Parola  [ ] Generic  [ ] ICStation  [X] FC-16  [ ] Custom (describe how wired)

## Steps to Reproduce
Using `parola.displayZoneText` paired with `PA_SCROLL_DOWN` and the zone set to inverted

## Expected Behaviour
The characters should scroll in from lit background into lit background, since everything is inverted

## Actual Behaviour
The characters scroll in from lit background into unlit background

## Code Demonstrating the Issue
````
parola.begin();

parola.setInvert( true );

parola.displayText( hm_message.current,
    hm_scroll.align,
    hm_scroll.speed,
    hm_scroll.pause,
    PA_SCROLL_DOWN );
````

**Comment by MajicDesigns** [comment]
Fixed and issued as v3.5.3
