### ISSUE TITLE
Would you add gravity or sin or a bit math / physics to bring the effect to the next level ? 

### ISSUE THREAD

**Issue by CCERocks** [MajicDesigns/MD_Parola#85]
Would you add gravity or sin or a bit math / physics to bring the effect to the next level ?  

dont mind if it premium Parola  :)

**Comment by MajicDesigns** [comment]
Thanks for  you suggestion, but it would be helpful if you describe what these animations would actually do.

**Comment by CCERocks** [comment]
> Thanks for  you suggestion, but it would be helpful if you describe what these hanges would actually look like.

Its just like a bouncing ball on left wall or right wall.. 

Lots of text effect i used to play during Adobe Flash player on desktop before been banned on mobile phone.. 

Just simple enhancement would be great :)
