### ISSUE TITLE
Feature Request ?

### ISSUE THREAD

**Issue by woeperbe** [MajicDesigns/MD_Parola#89]
I'am using latest version ;-)

Is there a method to set the hardware type in the Parola library just as in the MD_MAX72xx library ?

This works perfect in my code for the MD_MAX library but i cannot find the corresponding function call for Parola ?

M.setModuleType(MD_MAX72XX::ICSTATION_HW);

Thanks for your nice work

**Comment by MajicDesigns** [comment]
Set it when you create the object. Or you can access the MD_MAX72xx object and use that library’s methods. getGaphicObject() or something like that, from memory.

**Comment by woeperbe** [comment]
That works perfect ! You made my day :-)

	Matrix.getGraphicObject()->setModuleType(MD_MAX72XX::ICSTATION_HW);

Thanks again :-) :-)
