### ISSUE TITLE
Inclusion of extra constructor already available in MD_MAX72XX for multiple esp32 spi buses

### ISSUE THREAD

**Issue by John-Wallbank** [MajicDesigns/MD_Parola#98]
This is a suggestion to bring the MD_PAROLA library in step with MD_MAX72XX

Can you include this constructor to enable the use of multiple SPI buses on ESP32.  I think this was first introduced into the MD_MAX72XX library about 15 months ago.

MD_MAX72XX::moduleType_t mod, SPIClass &spi, uint8_t csPin, uint8_t numDevices = 1

**Comment by MajicDesigns** [comment]
Included in v3.6.0 release
